### PR TITLE
Fixed signing data containing special characters

### PR DESCRIPTION
**Pull request by donl**
Fixed plivo.create_signature when signing data containing special characters (e.g. sms message containing emoji 👦)

### CODE REVIEW

**Comment by tsudot** [comment]
@donl could you please add a test case for this change?

**Comment by donl** [comment]
I need some guidance on running the tests.  Trying to run the current tests on a fresh install, I get the the error below.  Do I need to be running the tests in a different manner?

dev@dev:~/nodejs/plivo-node/test$ node RestAPI.js 
/home/dev/.nvm/versions/v0.12.7/lib/node_modules/xmlbuilder/lib/XMLBuilder.js:17
        throw new Error("Root element needs a name");
              ^
Error: Root element needs a name
    at new XMLBuilder (/home/dev/.nvm/versions/v0.12.7/lib/node_modules/xmlbuilder/lib/XMLBuilder.js:17:15)
    at Object.module.exports.create (/home/dev/.nvm/versions/v0.12.7/lib/node_modules/xmlbuilder/lib/index.js:11:12)
    at Object.<anonymous> (/home/dev/nodejs/plivo-node/lib/plivo.js:7:22)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/dev/nodejs/plivo-node/test/RestAPI.js:3:13)

**Comment by tsudot** [comment]
You should follow this guide - https://github.com/plivo/plivo-node#tests

**Comment by donl** [comment]
I have added a couple create_signature tests.

**Comment by tsudot** [comment]
Thanks

**Pull request merged**
